### ISSUE TITLE
Doesnot work on arm.

### ISSUE THREAD

**Issue by leden1** [mickied/wxm-api-scripts#3]
Hi
Im running Debian server on Pi and i get error when when using docker image

`! wxm-retriever The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by mickied** [comment]
I've created a new version of the wxm-retriever Docker container that includes multi-platform support (AMD and ARM).  I changed the tag in the docker-compose file to pull the new container and push the changes to the [dockerized-with-grafana-and-mysql](https://github.com/mickied/wxm-api-scripts/tree/dockerized-with-grafana-and-mysql) branch.  It should work now, I tested it on my Raspberry Pi 4.

**Comment by leden1** [comment]
I tested and now it passes entire script, but grafana container never starts, it is in constant 'restarting' state.
I tested this on 2 different machines.
`CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS                          PORTS                                                    NAMES
84b0379d04dd   grafana/grafana:10.3.1         "/run.sh"                5 minutes ago   Restarting (1) 53 seconds ago                                                            grafana`

**Comment by mickied** [comment]
This is most likely a permissions issue.  Double-check that you set the `USER_ID` field in the `.env` file to the result of running `id -u`  from the terminal.

Then check the `docker/volumes` folder and the permissions on the folder for `grafana`.  It should be owned by the same user you're logged in with, or at least whatever user you entered the `USER_ID` for.

If not try:
`sudo chown -R myusername:myusername docker/volumes/grafana`

Replace `myusername` with yours.  Sometimes Grafana creates that folder and/or its subfolders as root.  At least on a Raspberry Pi.  I need to look into this more.

**Comment by leden1** [comment]
I guess it was permissions, don't know how since other 2 containers run just fine.
It works now, just need to change units. It shows correct number but wrong designation. (11F instead of 11C)
